apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: url-shorten-deployment
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: url-shorten-deployment
  minReplicas: 3
  maxReplicas: 7
  metrics:
  - type: Resource
    resource:
      name: cpu
      targetAverageUtilization: 50