apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
spec:
  selector:
    matchLabels:
      app: url-shortener
      tier: frontend
      track: stable
  template:
    metadata:
      labels:
        app: url-shortener
        tier: frontend
        track: stable
    spec:
      containers:
        - name: frontend
          image: gcr.io/PROJECT_ID/IMAGE:TAG
          resources:
          # You must specify requests for CPU to autoscale
          # based on CPU utilization
            requests:
              cpu: "150m"
          lifecycle:
            preStop:
              exec:
                command: ["/usr/sbin/nginx","-s","quit"]