apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
spec:
  selector:
    matchLabels:
      app: url-shortener
      tier: frontend
      track: stable
  replicas: 1
  template:
    metadata:
      labels:
        app: url-shortener
        tier: frontend
        track: stable
    spec:
      containers:
        - name: frontend
          image: gcr.io/PROJECT_ID/IMAGE:TAG
          lifecycle:
            preStop:
              exec:
                command: ["/usr/sbin/nginx","-s","quit"]