apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: url-shortener
      tier: backend
      track: stable
  template:
    metadata:
      labels:
        app: url-shortener
        tier: backend
        track: stable
    spec:
      volumes:
        - name: google-application-credentials
          secret:
            secretName: google-application-credentials
      containers:
        - name: backend
          image: gcr.io/PROJECT_ID/IMAGE:TAG
          ports:
            - name: http
              containerPort: 80
          volumeMounts:
            - name: google-application-credentials
              mountPath: /var/secrets/google
          env:
            - name: GOOGLE_APPLICATION_CREDENTIALS
              value: /var/secrets/google/key.json
