apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: url-shortener
      tier: backend
      track: stable
  strategy:
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 1
  minReadySeconds: 5
  template:
    metadata:
      labels:
        app: url-shortener
        tier: backend
        track: stable
    spec:
      containers:
        - name: backend
          image: gcr.io/PROJECT_ID/IMAGE:TAG
          ports:
            - name: http
              containerPort: 80