name: kubernete CD 


env:
  PROJECT_ID: ${{ secrets.GKE_PROJECT_ID }}
  GKE_CLUSTER: microservices
  GKE_ZONE: asia-east1-a
  IMAGE: backend

on:
  push:
    branches: [ microservices ]

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest

    permissions:
      contents: 'read'
      id-token: 'write'
      
    steps:
    - name: checkout files
      uses: actions/checkout@v3
      
    - name: Setup gcloud CLI
      uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
      with:
        version: '286.0.0'
        service_account_email: ${{ secrets.GCP_SA_EMAIL }}
        service_account_key: ${{ secrets.GCP_SA_KEY }}
        project_id: ${{ secrets.GCP_PROJECT_ID }}
        export_default_credentials: true
    
    - name: Info
      run: gcloud info
      
    - run: |-
        gcloud --quiet auth configure-docker
        
    - name: get cluster credential
      uses: google-github-actions/get-gke-credentials@fb08709ba27618c31c09e014e1d8364b02e5042e
      with:
        cluster_name: ${{ env.GKE_CLUSTER }}
        location: ${{ env.GKE_ZONE }}
        credentials: ${{ secrets.GKE_SA_KEY }}
      
    - name: Build the Docker image
      run: docker build . --file backend/Dockerfile --tag url-backend:$(date +%s)
      
    - name: Push docker image to google cloud  
      run: |-
        docker push "gcr.io/$PROJECT_ID/$IMAGE"
      
#   deploy:
#     name: Deploy
#     needs: [build]
#     runs-on: ubuntu-latest
    
    
